//! ASS, which every text subtitle encoder in ffmpeg speaks internally.
//!
//! Whatever format finally comes out, ffmpeg's text encoders all take ASS in
//! and convert on the way out. Two things have to be right for that. The
//! encoder needs an ASS header to parse for style definitions, and each
//! subtitle rect carries a dialogue line in ASS's field order.
//!
//! Neither is exposed by ffmpeg's public API, since the header builder is
//! internal, so both are written here.

use super::script::Cue;

/// Where a caption sits, using ASS's numeric alignment.
///
/// The numbering follows a numeric keypad, so 2 is bottom centre, which is
/// where subtitles belong.
const BOTTOM_CENTRE: u8 = 2;

/// ffmpeg's own ASS defaults.
///
/// Matching them exactly matters. Encoders that convert ASS into a plainer
/// format only emit styling markup when a style differs from these, so a
/// SubRip or WebVTT fixture built on anything else arrives wrapped in font
/// tags rather than as the plain text it is meant to be.
const FONT: &str = "Arial";
const FONT_SIZE: i32 = 16;
/// The reference canvas those defaults are sized against. Keeping it means a
/// font size of 16 stays proportionate however large the video is.
const PLAY_WIDTH: i32 = 384;
const PLAY_HEIGHT: i32 = 288;

/// Build the ASS header an encoder parses on open.
///
/// The layout mirrors what ffmpeg writes internally, because that is what its
/// parser expects to read back. Colours are ASS's `&Hbbggrr` order, which is
/// reversed against the usual `rrggbb`.
pub fn header() -> String {
    format!(
        "[Script Info]\n\
         ; Script generated by fakestream\n\
         ScriptType: v4.00+\n\
         PlayResX: {PLAY_WIDTH}\n\
         PlayResY: {PLAY_HEIGHT}\n\
         ScaledBorderAndShadow: yes\n\
         YCbCr Matrix: None\n\
         \n\
         [V4+ Styles]\n\
         Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, \
         OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, \
         ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, \
         Alignment, MarginL, MarginR, MarginV, Encoding\n\
         Style: Default,{FONT},{FONT_SIZE},&Hffffff,&Hffffff,&H0,&H0,\
         0,0,0,0,100,100,0,0,1,1,0,{BOTTOM_CENTRE},10,10,10,1\n\
         \n\
         [Events]\n\
         Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    )
}

/// Build the dialogue string a subtitle rect carries.
///
/// The field order matches ffmpeg's own `ff_ass_get_dialog`, which is read
/// order, layer, style, speaker, three margins, effect, then the text. Note it
/// is not a full `Dialogue:` line, and the timing is not in it either, since
/// that rides on the packet.
///
/// Line breaks are `\N`, ASS's hard break.
pub fn dialogue(cue: &Cue, read_order: usize) -> String {
    let text = cue.lines.join("\\N");
    format!("{read_order},0,Default,,0,0,0,,{}", escape(&text))
}

/// Neutralise the characters that would otherwise be read as ASS markup.
///
/// Braces open an override block, so text containing one would silently vanish
/// or corrupt the styling of everything after it.
fn escape(text: &str) -> String {
    text.replace('{', "\\{")
        .replace('}', "\\}")
        .replace('\n', "\\N")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cue(lines: &[&str]) -> Cue {
        Cue {
            start: 1.0,
            duration: 2.0,
            lines: lines.iter().map(|line| line.to_string()).collect(),
        }
    }

    #[test]
    fn the_header_declares_the_default_style() {
        let header = header();
        assert!(header.contains("[V4+ Styles]"));
        assert!(header.contains("Style: Default,"));
        assert!(header.contains("[Events]"));
    }

    #[test]
    fn the_header_matches_ffmpeg_defaults() {
        // Diverging here makes ffmpeg wrap plain formats in font markup, so
        // these values are load bearing rather than cosmetic.
        let header = header();
        assert!(header.contains("PlayResX: 384"));
        assert!(header.contains("PlayResY: 288"));
        assert!(header.contains("Default,Arial,16,"));
    }

    #[test]
    fn a_dialogue_has_nine_fields_before_the_text() {
        // Read order, layer, style, speaker, three margins and an effect, then
        // the text. Getting the count wrong shifts the text into a field the
        // parser reads as something else.
        let line = dialogue(&cue(&["Lorem ipsum"]), 0);
        let fields: Vec<&str> = line.splitn(9, ',').collect();
        assert_eq!(fields.len(), 9);
        assert_eq!(fields[8], "Lorem ipsum");
    }

    #[test]
    fn read_order_is_carried_through() {
        assert!(dialogue(&cue(&["a"]), 7).starts_with("7,"));
    }

    #[test]
    fn several_lines_become_hard_breaks() {
        let line = dialogue(&cue(&["first", "second"]), 0);
        assert!(line.ends_with("first\\Nsecond"));
    }

    #[test]
    fn braces_are_escaped_so_they_are_not_read_as_markup() {
        // An unescaped brace opens an override block and swallows the text.
        let line = dialogue(&cue(&["a {b} c"]), 0);
        assert!(line.ends_with("a \\{b\\} c"));
    }
}
